# Generated by go2rpm 1.2
%bcond_without check

# https://github.com/cosandr/go-check-updates
%global goipath         github.com/cosandr/go-check-updates
Version:                0
%global tag             v1.0-rc1

%gometa

%global common_description %{expand:
Check for updates and expose them through API or websocket.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           go-check-updates
Release:        1%{?dist}
Summary:        Check for updates and expose them through API or websocket

License:        MIT
URL:            %{gourl}
Source0:        %{gosource}

# BuildRequires:  golang(github.com/alexflint/go-arg)
# BuildRequires:  golang(github.com/coreos/go-systemd/v22/activation)
# BuildRequires:  golang(github.com/gorilla/websocket)
# BuildRequires:  golang(github.com/sirupsen/logrus)
# BuildRequires:  golang(github.com/sirupsen/logrus/hooks/writer)
# BuildRequires:  golang(golang.org/x/sys/unix)

%description
%{common_description}

%gopkg

%prep
%goprep

%build
go mod vendor
%gobuild -o %{gobuilddir}/bin/%{name} %{goipath}
./setup.sh install systemd --pkg-name %{name} --systemd-path ./ --tmp-path ./tmp --no-log --no-cache

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
install -m 0755 -vd                     %{buildroot}/usr/lib/systemd/system
install -m 0644 -vp %{name}.service   %{buildroot}/usr/lib/systemd/system/
install -m 0644 -vp %{name}.socket    %{buildroot}/usr/lib/systemd/system/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc README.md
%{_bindir}/*
/usr/lib/systemd/system/%{name}.service
/usr/lib/systemd/system/%{name}.socket

%gopkgfiles

%changelog
* Wed Nov 04 11:37:15 CET 2020 Andrei Costescu <andrei@costescu.no> - v1.0-rc1-1
- Initial package